### ISSUE TITLE
missing input warning for `changelog`

### ISSUE THREAD

**Issue by koderisch** [peterchanxyz/slack-markdown-action#1]
When running the action github warns about the input `changelog` not being valid.

Warning displayed: `Unexpected input(s) 'changelog', valid inputs are ['text']`

This is due to missing `changelog` input  in actions.yml

**Comment by koderisch** [comment]
I have a PR ready for this. Proposed changed `action.yml`:

```
name: 'Slackapi Changelog'
description: "Convert changelog markdown to Slack's mrkdwn"
inputs:
  text:
    description: 'The title text to show'
    required: true
  changelog:
    description: 'The changelog markdown text to convert'
    required: true
outputs:
  payload:
    description: 'The content payload for slackapi'
runs:
  using: 'node16'
  main: "dist/index.js"
branding:
  icon: 'send'
  color: 'blue'
```
